import pandas as pd
import os

### Generate phenotype files for each cluster based clusters generated by cluster_phenotypes_by_pca_loadings.py 
# Load cluster assignment CSV from PCA
df = pd.read_csv("pca_loadings_dend(0.35).csv")  # Update filename if needed

# Load the full phenotype matrix (assumes traits start from 5th column)
full_pheno = blups_SC_imputed_k7.iloc[:, 4:]

# Output directory (create if it doesn't exist)
out_dir = "impk7_pca_clusters"
os.makedirs(out_dir, exist_ok=True)

# Process each cluster
for cluster_id in df["Cluster"].unique():
    print(f"Processing Cluster ID: {cluster_id}")
    
    try:
        cluster_num = cluster_id.split()[-1]  # Get the numeric part of "Cluster X"
    except AttributeError:
        cluster_num = cluster_id

    # Subset DataFrame for current cluster
    subset = df[df["Cluster"] == cluster_id]

    # Extract column numbers (assumed 0-based indexing from our PCA CSV)
    cols = subset["Column Number"].tolist()

    print(f"Cluster {cluster_num}: Column Numbers = {cols}")

    # Validate column index range
    cols = [col for col in cols if 0 <= col < len(full_pheno.columns)]

    # Select and export phenotype columns
    out_df = full_pheno.iloc[:, cols]
    out_file = os.path.join(out_dir, f"cluster_{cluster_num}_impk7_pca_cut0.35.phenos.txt")
    out_df.to_csv(out_file, sep="\t", index=False, header=False)

    print(f"Saved Cluster {cluster_num} phenotypes to {out_file}")